/* Untyped file generated by genType. */

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

import * as page_indexBS from './page_index.bs';

export const page_index = ReasonReact.wrapReasonForJs(
  page_indexBS.component,
  (function _(jsProps) {
     return page_indexBS.make(jsProps.children);
  }));

export default page_index;
