/* Untyped file generated by genType. */

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

import * as page_typographyBS from './page_typography.bs';

export const page_typography = ReasonReact.wrapReasonForJs(
  page_typographyBS.component,
  (function _(jsProps) {
     return page_typographyBS.make(jsProps.children);
  }));

export default page_typography;
